#%RAML 1.0 Library

types: 
  ProductDetails:
    properties:
      order_id: 
        type: integer
        required: false
      store_id: 
        type: integer
        required: true
      store_name: 
        type: string
        required: false
      store_address: 
        type: string
        required: false
      store_distance: 
        type: number
        required: true
      store_contact_number:
        type: string
        required: false
      product_type_id: 
        type: string
        required: false
      quantity: 
        type: integer
        required: true


